"""Auto-generated by fix(). Description: Fixed: broken"""

__test__ = False

from openprogram.agentic_programming.function import agentic_function
from openprogram.agentic_programming.runtime import Runtime

def broken():
    return 'fixed'
